#ifndef SPN_RMGUI_UI_MANAGER_H
#define SPN_RMGUI_UI_MANAGER_H
#include <memory>
#include <vector>
#include "../core/spn_canvas.h"
#include "../spn_ui_event.h"
#include "spn_rmgui_widget.h"

namespace spn::rmgui {
	class UiManager {
	public:
		inline static UiManager& GetInstance() {
			static UiManager instance;
			return instance;
		}

		void Display(spn::Canvas* canvas) {
			int i = 0;
			int focusIdx = -1;
			Widget* focused = nullptr;
			for (const auto& w : widgets) {
				if (w->HasFocus()) {
					focused = w.get();
				}
				else {
					w->Display(canvas);
				}
			}
			if (focused != nullptr) {
				focused->Display(canvas);
			}

		}

		//void Display2() {
		//	int i = 0;
		//	int focusIdx = -1;
		//	int count = 0;
		//	for (const auto& w : widgets) {
		//		if (w->HasFocus()) {
		//			focusIdx = i;
		//			++count;
		//		}
		//		++i;
		//	}
		//	//std::cout << count;
		//}

		bool HandleUiEvent(spn::ui::UiEvent& uie) {
			if (uie.eventType == spn::ui::UiEventType::None) {
				return false;
			}

			for (auto it = widgets.rbegin(); it != widgets.rend(); ++it) {
				spn::rmgui::Widget* w = it->get();
				if (!w->IsSubscribed(uie.eventType)) {
					continue;
				}

				if (DispatchToWidget(*w, uie)) {
					return true;
				}
			}
			return false;
		}

		bool DispatchToWidget(spn::rmgui::Widget& w, spn::ui::UiEvent& e) {
			switch (e.eventType) {
			case spn::ui::UiEventType::MouseDown:
				return w.OnMouseDown(e.mouseButton, e.mouseX, e.mouseY);

			case spn::ui::UiEventType::MouseUp:
				return w.OnMouseUp(e.mouseButton, e.mouseX, e.mouseY);

			case spn::ui::UiEventType::MouseMove:
				return w.OnMouseMove(e.mouseX, e.mouseY);

			case spn::ui::UiEventType::MouseDrag:
				return w.OnMouseDrag(e.mouseX, e.mouseY);

			case spn::ui::UiEventType::CharInput:
				return w.OnCharInput(e.character);
			case spn::ui::UiEventType::ActionKeyDown:
				return w.OnActionKeyDown(e.keyCode);
			case spn::ui::UiEventType::ActionKeyUp:
				return w.OnActionKeyUp(e.keyCode);
			}

			return false;
		}




		// This function is generated by ChatGPT AI agent
		/*template<typename T, typename... Args>
		T* CreateWidget(Args&&... args) {
			static_assert(std::is_base_of_v<Widget, T>, "T must derive from Widget");

			auto w = std::make_unique<T>(std::forward<Args>(args)...);
			T* ptr = w.get();
			widgets.emplace_back(std::move(w));
			return ptr;
		}*/

		//This function is an optimization of the AI generated function
		template<typename T>
		T* CreateWidget() {
			static_assert(std::is_base_of_v<Widget, T>, "T must derive from Widget");
			auto w = std::make_unique<T>();
			T* ptr = w.get();
			widgets.emplace_back(std::move(w));
			return ptr;
		}


	private:
		std::vector<std::unique_ptr<Widget>> widgets;
		UiManager() = default;
		UiManager(const UiManager&) = delete;
		UiManager& operator=(const UiManager&) = delete;
	};

}

#endif