// ============================================
// This file is generated by AI (ChatGPT, OpenAI).
// Please review and adapt as needed before use.
// ============================================

#ifndef SPNRNG_H
#define SPNRNG_H

#include <random>
#include <chrono>
namespace spn {
    class RandomGen {
    public:
        // Get the singleton instance
        inline static RandomGen& GetInstance() {
            static RandomGen instance;
            return instance;
        }

        // Generate any random integer
        inline int Generate() {
            return distribution(rng);
        }

        // Generate random integer in [min, max]
        inline int GenerateInRange(int min, int max) {
            std::uniform_int_distribution<int> range_dist(min, max);
            return range_dist(rng);
        }

        inline std::mt19937& GetRng() {
            return rng;
        }

        inline std::uniform_int_distribution<int>& GetDistribution() {
            return distribution;
        }

    private:
        // Private constructor
        RandomGen()
            : rng(std::chrono::steady_clock::now().time_since_epoch().count())
        {
        }

        // Delete copy constructor and assignment operator
        RandomGen(const RandomGen&) = delete;
        RandomGen& operator=(const RandomGen&) = delete;
        std::mt19937 rng;
        std::uniform_int_distribution<int> distribution;

    };
}


#endif
